// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVgW7zMjCUEPZzlV1SjKF0rC09var0voM',
    appId: '1:519768581909:web:c8d2f068e1dabd72f72b1c',
    messagingSenderId: '519768581909',
    projectId: 'mazijchat',
    authDomain: 'mazijchat.firebaseapp.com',
    storageBucket: 'mazijchat.appspot.com',
    measurementId: 'G-1YVJP95ZD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_yN3wp15tIXPt3TkBBt642IR_88pBZe4',
    appId: '1:519768581909:android:4c29e7f6c8166f82f72b1c',
    messagingSenderId: '519768581909',
    projectId: 'mazijchat',
    storageBucket: 'mazijchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp3Dx9FkACn6hse1k-kz1SqtmVyENAe94',
    appId: '1:519768581909:ios:fcdf21dcbe7ba889f72b1c',
    messagingSenderId: '519768581909',
    projectId: 'mazijchat',
    storageBucket: 'mazijchat.appspot.com',
    iosClientId: '519768581909-kji7c53titm0s3k3ho1a9uvhouni90ig.apps.googleusercontent.com',
    iosBundleId: 'com.mazij.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp3Dx9FkACn6hse1k-kz1SqtmVyENAe94',
    appId: '1:519768581909:ios:fcdf21dcbe7ba889f72b1c',
    messagingSenderId: '519768581909',
    projectId: 'mazijchat',
    storageBucket: 'mazijchat.appspot.com',
    iosClientId: '519768581909-kji7c53titm0s3k3ho1a9uvhouni90ig.apps.googleusercontent.com',
    iosBundleId: 'com.mazij.app',
  );
}
